TH MOVIMENTACAO AS (
            SELECT
                    doc.docu_dk AS alrt_docu_dk,
                            doc.docu_nr_mp AS alrt_docu_nr_mp,
                                    doc.docu_nr_externo AS alrt_docu_nr_externo,
                                            doc.docu_tx_etiqueta AS alrt_docu_etiqueta,
                                                    classe.cldc_ds_classe AS alrt_docu_classe,
                                                            max(coalesce(
                                                                            mov.movi_dt_recebimento_guia, mov.movi_dt_envio_guia, mov.movi_dt_criacao_guia
                                                                                    )) AS dt_guia,
                                                                    doc.docu_orgi_orga_dk_responsavel AS alrt_orgi_orga_dk,
                                                                            classe.cldc_ds_hierarquia AS alrt_classe_hierarquia
                                                                                    FROM exadata.mcpr_documento doc
                                                                                                JOIN exadata.mcpr_item_movimentacao it_mov ON it_mov.item_docu_dk = doc.docu_dk
                                                                                                            JOIN exadata.mcpr_movimentacao mov ON mov.movi_dk = it_mov.item_movi_dk
                                                                                                                        JOIN exadata_aux.mmps_classe_hierarquia classe ON cast(classe.cldc_dk AS BIGINT) = doc.docu_cldc_dk
                                                                                                                                WHERE 
                                                                                                                                            doc.docu_tpst_dk = 3
                                                                                                                                                        AND doc.docu_fsdc_dk = 1
                                                                                                                                                                GROUP BY 
                                                                                                                                                                            doc.docu_dk,
                                                                                                                                                                                        doc.docu_nr_mp,
                                                                                                                                                                                                    doc.docu_nr_externo,
                                                                                                                                                                                                                doc.docu_tx_etiqueta,
                                                                                                                                                                                                                            classe.cldc_ds_classe,
                                                                                                                                                                                                                                        doc.docu_orgi_orga_dk_responsavel,
                                                                                                                                                                                                                                                    classe.cldc_ds_hierarquia
                                                                                                                                                                                                                                                    ), LAST_BAIXA AS (
                                                                                                                                                                                                                                                                SELECT 
                                                                                                                                                                                                                                                                        doc.docu_dk AS laba_docu_dk,
                                                                                                                                                                                                                                                                                sub_a.stao_nr_dias_prazo as stao_nr_dias_prazo
                                                                                                                                                                                                                                                                                    FROM exadata.mcpr_documento doc
                                                                                                                                                                                                                                                                                            JOIN exadata.mcpr_vista vist ON vist.vist_docu_dk = doc.docu_dk
                                                                                                                                                                                                                                                                                                    JOIN exadata.mcpr_andamento anda ON vist.vist_dk = anda.pcao_vist_dk
                                                                                                                                                                                                                                                                                                            JOIN exadata.mcpr_sub_andamento sub_a ON sub_a.stao_pcao_dk = anda.pcao_dk
                                                                                                                                                                                                                                                                                                                    JOIN exadata_aux.mmps_tp_andamento tp_a ON sub_a.stao_tppr_dk = tp_a.id
                                                                                                                                                                                                                                                                                                                            JOIN (
                                                                                                                                                                                                                                                                                                                                            SELECT 
                                                                                                                                                                                                                                                                                                                                                            vist.vist_docu_dk as vist_docu_dk, 
                                                                                                                                                                                                                                                                                                                                                                            max(anda.pcao_dt_andamento) as pcao_dt_andamento
                                                                                                                                                                                                                                                                                                                                                                                        FROM exadata.mcpr_vista vist
                                                                                                                                                                                                                                                                                                                                                                                                        JOIN exadata.mcpr_andamento anda ON vist.vist_dk = anda.pcao_vist_dk
                                                                                                                                                                                                                                                                                                                                                                                                                        JOIN exadata.mcpr_sub_andamento sub_a ON sub_a.stao_pcao_dk = anda.pcao_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                        JOIN exadata_aux.mmps_tp_andamento tp_a ON sub_a.stao_tppr_dk = tp_a.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                    GROUP BY vist.vist_docu_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) inner_anda ON 
                                                                                                                                                                                                                                                                                                                                        inner_anda.vist_docu_dk = doc.docu_dk 
                                                                                                                                                                                                                                                                                                                                                    AND anda.pcao_dt_andamento = inner_anda.pcao_dt_andamento
                                                                                                                                                                                                                                                                                                                                                        WHERE tp_a.id_pai IN (6363, 6519)
                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                    SELECT
                                                                                                                                                                                                                                                        mov.alrt_docu_dk,
                                                                                                                                                                                                                                                            mov.alrt_docu_nr_mp,
                                                                                                                                                                                                                                                                mov.alrt_docu_nr_externo,
                                                                                                                                                                                                                                                                    mov.alrt_docu_etiqueta,
                                                                                                                                                                                                                                                                        mov.alrt_docu_classe,
                                                                                                                                                                                                                                                                            date_add(mov.dt_guia, cast(laba.stao_nr_dias_prazo AS INT)) AS alrt_docu_date,
                                                                                                                                                                                                                                                                                mov.alrt_orgi_orga_dk,
                                                                                                                                                                                                                                                                                    mov.alrt_classe_hierarquia,
                                                                                                                                                                                                                                                                                        datediff(now(), date_add(mov.dt_guia, cast(laba.stao_nr_dias_prazo AS INT))) AS alrt_dias_passados,
                                                                                                                                                                                                                                                                                            'Baixas à DP em atraso' AS alrt_descricao,
                                                                                                                                                                                                                                                                                                'BDPA' AS alrt_sigla
                                                                                                                                                                                                                                                                                                FROM MOVIMENTACAO mov
                                                                                                                                                                                                                                                                                                    JOIN (
                                                                                                                                                                                                                                                                                                                    SELECT docu_dk,
                                                                                                                                                                                                                                                                                                                                coalesce(mov.movi_dt_recebimento_guia, mov.movi_dt_envio_guia, mov.movi_dt_criacao_guia) AS dt_guia,
                                                                                                                                                                                                                                                                                                                                            movi_orga_dk_destino
                                                                                                                                                                                                                                                                                                                                                    FROM exadata.mcpr_documento doc
                                                                                                                                                                                                                                                                                                                                                            JOIN exadata.mcpr_item_movimentacao it_mov ON it_mov.item_docu_dk = doc.docu_dk
                                                                                                                                                                                                                                                                                                                                                                    JOIN exadata.mcpr_movimentacao mov ON mov.movi_dk = it_mov.item_movi_dk
                                                                                                                                                                                                                                                                                                                                                                        ) all_mov ON 
                                                                                                                                                                                                                                                                                                            all_mov.docu_dk = mov.alrt_docu_dk 
                                                                                                                                                                                                                                                                                                                    AND all_mov.dt_guia = mov.dt_guia
                                                                                                                                                                                                                                                                                                                        JOIN exadata.mprj_orgao_ext oext ON all_mov.movi_orga_dk_destino = oext.orge_orga_dk
                                                                                                                                                                                                                                                                                                                            JOIN LAST_BAIXA laba ON laba.laba_docu_dk = mov.alrt_docu_dk
                                                                                                                                                                                                                                                                                                                            WHERE
                                                                                                                                                                                                                                                                                                                                oext.orge_tpoe_dk IN (54,68,60,61) -- garante que orgão de destino da última guia é órgão externo e que é do tipo: POLÍCIA FEDERAL, POLÍCIA MILITAR RJ, POLÍCIA CIVIL RJ - DELEGACIA POLICIAL ou POLÍCIA CIVIL RJ - DELEGACIA POLICIAL (DP LEGAL) 
                                                                                                                                                                                                                                                                                                                                    AND date_add(mov.dt_guia, cast(laba.stao_nr_dias_prazo AS INT)) < now()WITH MOVIMENTACAO AS (
                                                                                                                                                                                                                                                                                                                                                SELECT
                                                                                                                                                                                                                                                                                                                                                        doc.docu_dk AS alrt_docu_dk,
                                                                                                                                                                                                                                                                                                                                                                doc.docu_nr_mp AS alrt_docu_nr_mp,
                                                                                                                                                                                                                                                                                                                                                                        doc.docu_nr_externo AS alrt_docu_nr_externo,
                                                                                                                                                                                                                                                                                                                                                                                doc.docu_tx_etiqueta AS alrt_docu_etiqueta,
                                                                                                                                                                                                                                                                                                                                                                                        classe.cldc_ds_classe AS alrt_docu_classe,
                                                                                                                                                                                                                                                                                                                                                                                                max(coalesce(
                                                                                                                                                                                                                                                                                                                                                                                                                mov.movi_dt_recebimento_guia, mov.movi_dt_envio_guia, mov.movi_dt_criacao_guia
                                                                                                                                                                                                                                                                                                                                                                                                                        )) AS dt_guia,
                                                                                                                                                                                                                                                                                                                                                                                                        doc.docu_orgi_orga_dk_responsavel AS alrt_orgi_orga_dk,
                                                                                                                                                                                                                                                                                                                                                                                                                classe.cldc_ds_hierarquia AS alrt_classe_hierarquia
                                                                                                                                                                                                                                                                                                                                                                                                                        FROM exadata.mcpr_documento doc
                                                                                                                                                                                                                                                                                                                                                                                                                                    JOIN exadata.mcpr_item_movimentacao it_mov ON it_mov.item_docu_dk = doc.docu_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                JOIN exadata.mcpr_movimentacao mov ON mov.movi_dk = it_mov.item_movi_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                            JOIN exadata_aux.mmps_classe_hierarquia classe ON cast(classe.cldc_dk AS BIGINT) = doc.docu_cldc_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.docu_tpst_dk = 3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            AND doc.docu_fsdc_dk = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GROUP BY 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.docu_dk,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            doc.docu_nr_mp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        doc.docu_nr_externo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.docu_tx_etiqueta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                classe.cldc_ds_classe,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            doc.docu_orgi_orga_dk_responsavel,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        classe.cldc_ds_hierarquia
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ), LAST_BAIXA AS (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            doc.docu_dk AS laba_docu_dk,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sub_a.stao_nr_dias_prazo as stao_nr_dias_prazo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FROM exadata.mcpr_documento doc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                JOIN exadata.mcpr_vista vist ON vist.vist_docu_dk = doc.docu_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        JOIN exadata.mcpr_andamento anda ON vist.vist_dk = anda.pcao_vist_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                JOIN exadata.mcpr_sub_andamento sub_a ON sub_a.stao_pcao_dk = anda.pcao_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        JOIN exadata_aux.mmps_tp_andamento tp_a ON sub_a.stao_tppr_dk = tp_a.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                JOIN (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                vist.vist_docu_dk as vist_docu_dk, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                max(anda.pcao_dt_andamento) as pcao_dt_andamento
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FROM exadata.mcpr_vista vist
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            JOIN exadata.mcpr_andamento anda ON vist.vist_dk = anda.pcao_vist_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            JOIN exadata.mcpr_sub_andamento sub_a ON sub_a.stao_pcao_dk = anda.pcao_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            JOIN exadata_aux.mmps_tp_andamento tp_a ON sub_a.stao_tppr_dk = tp_a.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        GROUP BY vist.vist_docu_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) inner_anda ON 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            inner_anda.vist_docu_dk = doc.docu_dk 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AND anda.pcao_dt_andamento = inner_anda.pcao_dt_andamento
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHERE tp_a.id_pai IN (6363, 6519)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mov.alrt_docu_dk,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mov.alrt_docu_nr_mp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mov.alrt_docu_nr_externo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mov.alrt_docu_etiqueta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mov.alrt_docu_classe,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                date_add(mov.dt_guia, cast(laba.stao_nr_dias_prazo AS INT)) AS alrt_docu_date,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mov.alrt_orgi_orga_dk,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mov.alrt_classe_hierarquia,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            datediff(now(), date_add(mov.dt_guia, cast(laba.stao_nr_dias_prazo AS INT))) AS alrt_dias_passados,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Baixas à DP em atraso' AS alrt_descricao,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'BDPA' AS alrt_sigla
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FROM MOVIMENTACAO mov
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        JOIN (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT docu_dk,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    coalesce(mov.movi_dt_recebimento_guia, mov.movi_dt_envio_guia, mov.movi_dt_criacao_guia) AS dt_guia,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                movi_orga_dk_destino
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FROM exadata.mcpr_documento doc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                JOIN exadata.mcpr_item_movimentacao it_mov ON it_mov.item_docu_dk = doc.docu_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        JOIN exadata.mcpr_movimentacao mov ON mov.movi_dk = it_mov.item_movi_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) all_mov ON 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                all_mov.docu_dk = mov.alrt_docu_dk 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AND all_mov.dt_guia = mov.dt_guia
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            JOIN exadata.mprj_orgao_ext oext ON all_mov.movi_orga_dk_destino = oext.orge_orga_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                JOIN LAST_BAIXA laba ON laba.laba_docu_dk = mov.alrt_docu_dk
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHERE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    oext.orge_tpoe_dk IN (54,68,60,61) -- garante que orgão de destino da última guia é órgão externo e que é do tipo: POLÍCIA FEDERAL, POLÍCIA MILITAR RJ, POLÍCIA CIVIL RJ - DELEGACIA POLICIAL ou POLÍCIA CIVIL RJ - DELEGACIA POLICIAL (DP LEGAL) 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AND date_add(mov.dt_guia, cast(laba.stao_nr_dias_prazo AS INT)) < now()
